default:
  push_kubernetes: false
  push_images: true

agent:
  name: test-agent

plugin:
  callback: 127.0.0.1:8090

mysql:
  host: peng
  user: root
  password: Pixiu868686
  port: 3306
  name: rainbow

register:
  repository: registry.cn-hangzhou.aliyuncs.com
  namespace: pixiucloud
  username: aliyun9626582710
  password: kubevulpes123

kubernetes:
  version: v1.23.6

images:
  - docker.io/nginx:latest
