default:
  push_kubernetes: false
  push_images: false

mysql:
  host: peng
  user: root
  password: Pixiu868686
  port: 3306
  name: rainbow

register:
  target:
    username: test
    password: test
    registry: harbor.cloud.pixiuio.com
  source:
    username: test
    password: test
    registry: harbor.cloud.pixiuio.com

kubernetes:
  version: v1.23.6

images:
  - docker.io/nginx:latest
