default:
  push_kubernetes: false
  push_images: false

agent:
  name: test-agent

plugin:
  callback: 127.0.0.1:8090

mysql:
  host: peng
  user: root
  password: Pixiu868686
  port: 3306
  name: rainbow

registry:
  repository: harbor.cloud.pixiuio.com
  namespace: pixiucloud
  username: test
  password: test

kubernetes:
  version: v1.23.6

images:
  - docker.io/nginx:latest
